add module exception
bayesian-optimization/BayesianOptimization pull request #506
Opened 2024-07-25 12:00 UTC by phi-friday

With this PR, I hope to make it easier to catch errors while using `bayesian-optimization`.

2024-09-07 18:02 UTC, till-m requested changes
Could you add an `exception.rst` file in the docs such that we have these visible to users in the documentation?

2024-09-08 08:28 UTC, phi-friday commented on bayes_opt/exception.py
> +__all__ = [
When importing objects like `from A import *`, only the objects defined in `__all__` should be imported.
I usually leave this in, but I'll remove it if it's not needed.

2024-09-08 08:45 UTC, phi-friday commented
Added `reference/exception.rst`.

2024-09-08 09:04 UTC, till-m approved these changes

2024-09-08 09:04 UTC, merged